### ISSUE TITLE
Receive fwrite error exception

### ISSUE THREAD

**Issue by ghost** [php-amqplib/RabbitMqBundle#19]
Hi, 
I wrote some producer/consumer commands in sf2, and when I excuted a certain producer command, 
I continuously receive the following error exception:

```
[ErrorException]                                                                                                                                              
  Notice: fwrite(): send of 10 bytes failed with errno=11 Resource temporarily unavailable in /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php line 141  






PHP Fatal error:  Uncaught exception 'Exception' with message 'Error reading data. Recevived 0 instead of expected 1 bytes' in /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:64
Stack trace:
#0 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(95): PhpAmqpLib\Wire\AMQPReader->rawread(1)
#1 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php(260): PhpAmqpLib\Wire\AMQPReader->read_octet()
#2 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php(280): PhpAmqpLib\Connection\AMQPConnection->wait_frame()#3 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(119): PhpAmqpLib\Connection\AMQPConnection->wait_channel(0)
#4 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(225): PhpAmqpLib\Channel\AbstractChannel->next_frame()#5 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php(321): PhpAmq in /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php on line 64
Fatal error: Uncaught exception 'Exception' with message 'Error reading data. Recevived 0 instead of expected 1 bytes' in /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:64 
Stack trace:
#0 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(95): PhpAmqpLib\Wire\AMQPReader->rawread(1) #1 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php(260): PhpAmqpLib\Wire\AMQPReader->read_octet()
#2 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php(280): PhpAmqpLib\Connection\AMQPConnection->wait_frame()
#3 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(119): PhpAmqpLib\Connection\AMQPConnection->wait_channel(0)
#4 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(225): PhpAmqpLib\Channel\AbstractChannel->next_frame()
#5 /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPConnection.php(321): PhpAmq in /root/convert_src/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php on line 64
```

It would throw exception until it had published about 88000 or above messages,

Thanks in advanced.

**Comment by ramunasd** [comment]
This looks like library exception. Please report issue there if it still occurs.
