### ISSUE TITLE
Upgrading from v1.5 to v1.7 non-existent server

### ISSUE THREAD

**Issue by eddiejaoude** [php-amqplib/RabbitMqBundle#297]
Error:

``` bash
 You have requested a non-existent service "old_sound_rabbit_mq.connection_factory.default". (Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException)
```

Any ideas what this could be after the upgrade?

**Comment by eddiejaoude** [comment]
Same issue on version `1.6`

**Comment by videlalvaro** [comment]
Maybe this is related to this change? https://github.com/videlalvaro/RabbitMqBundle/pull/233 

ping @bburnichon

**Comment by eddiejaoude** [comment]
Hmm...

I am using the same config `old_sound_rabbit_mq.connection.default` which matches https://github.com/videlalvaro/RabbitMqBundle/pull/233/files#diff-c5e7323b85deec1330e358d14f0041a3L96

This is not available `old_sound_rabbit_mq.connection_factory.default` but we don't call that in our code https://github.com/videlalvaro/RabbitMqBundle/pull/233/files#diff-c5e7323b85deec1330e358d14f0041a3R81

Do I need to definite anything else / different?

**Comment by eddiejaoude** [comment]
PS. thanks for quick reply :+1:

**Comment by eddiejaoude** [comment]
@videlalvaro After more investigation it appears that is the issue, particularly this line `$definition->setPublic(false);` https://github.com/videlalvaro/RabbitMqBundle/pull/233/files#diff-c5e7323b85deec1330e358d14f0041a3R80

If I set this to `true` all works fine. However, we are not calling this service in our code `old_sound_rabbit_mq.connection_factory.default`.

Stack trace...

```bash
exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'You have requested a non-existent service "old_sound_rabbit_mq.connection_factory.default".' in vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:317
  ╳  Stack trace:
  ╳  #0 vendor/polishsymfonycommunity/symfony-mocker-container/src/PSS/SymfonyMockerContainer/DependencyInjection/MockerContainer.php(56): Symfony\Component\DependencyInjection\Container->get('old_sound_rabbi...', 1)
  ╳  #1 var/cache/test/appTestDebugProjectContainer.php(2829): PSS\SymfonyMockerContainer\DependencyInjection\MockerContainer->get('old_sound_rabbi...')
  ╳  #2 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(326): appTestDebugProjectContainer->getOldSoundRabbitMq_Connection_DefaultService()
  ╳  #3 vendor/polishsymfonycommunity/symfony-mocker-container/src/PSS/SymfonyMockerContainer/DependencyInjection/MockerContainer.php(56): Symfony\Component\DependencyInjection\Container->get('old_sound_rabbi...', 1)
  ╳  #4 var/cache/test/appTestDebugProjectContainer.php(2930): PSS\SymfonyMockerContainer\DependencyInjection\MockerContainer->get('old_sound_rabbi...')
  ╳  #5 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(326): appTestDebugProjectContainer->getOldSoundRabbitMq_ValidateFileProducerService()
  ╳  #6 vendor/polishsymfonycommunity/symfony-mocker-container/src/PSS/SymfonyMockerContainer/DependencyInjection/MockerContainer.php(56): Symfony\Component\DependencyInjection\Container->get('old_sound_rabbi...', 1)
  ╳  #7 var/cache/test/appTestDebugProjectContainer.php(3045): PSS\SymfonyMockerContainer\DependencyInjection\MockerContainer->get('old_sound_rabbi...')
  ╳  #8 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(326): appTestDebugProjectContainer->getQueue_ValidateFile_AdapterService()
  ╳  #9 vendor/polishsymfonycommunity/symfony-mocker-container/src/PSS/SymfonyMockerContainer/DependencyInjection/MockerContainer.php(56): Symfony\Component\DependencyInjection\Container->get('queue.validate_...', 1)
  ╳  #10 var/cache/test/appTestDebugProjectContainer.php(3032): PSS\SymfonyMockerContainer\DependencyInjection\MockerContainer->get('queue.validate_...')
  ╳  #11 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(326): appTestDebugProjectContainer->getQueue_ValidateFileService()
  ╳  #12 vendor/polishsymfonycommunity/symfony-mocker-container/src/PSS/SymfonyMockerContainer/DependencyInjection/MockerContainer.php(56): Symfony\Component\DependencyInjection\Container->get('queue.validate_...', 1)
  ╳  #13 src/Crossrail/Behat/Traits/Queue.php(34): PSS\SymfonyMockerContainer\DependencyInjection\MockerContainer->get('queue.validate_...')
  ╳  #14 src/Crossrail/Bundle/QueueBundle/Behat/FeatureContext.php(26): Crossrail\Bundle\QueueBundle\Behat\FeatureContext->setQueue()
  ╳  #15 [internal function]: Crossrail\Bundle\QueueBundle\Behat\FeatureContext->before(Object(Behat\Behat\Hook\Scope\BeforeScenarioScope))
  ╳  #16 vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(99): call_user_func_array(Array, Array)
  ╳  #17 vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(54): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Testwork\Hook\Call\HookCall))
  ╳  #18 vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(125): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall(Object(Behat\Testwork\Hook\Call\HookCall))
  ╳  #19 vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(80): Behat\Testwork\Call\CallCenter->handleCall(Object(Behat\Testwork\Hook\Call\HookCall))
  ╳  #20 vendor/behat/behat/src/Behat/Testwork/Hook/HookDispatcher.php(74): Behat\Testwork\Call\CallCenter->makeCall(Object(Behat\Testwork\Hook\Call\HookCall))
  ╳  #21 vendor/behat/behat/src/Behat/Testwork/Hook/HookDispatcher.php(58): Behat\Testwork\Hook\HookDispatcher->dispatchHook(Object(Behat\Behat\Hook\Scope\BeforeScenarioScope), Object(Behat\Behat\Hook\Call\BeforeScenario))
  ╳  #22 vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(64): Behat\Testwork\Hook\HookDispatcher->dispatchScopeHooks(Object(Behat\Behat\Hook\Scope\BeforeScenarioScope))
  ╳  #23 vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(90): Behat\Behat\Hook\Tester\HookableScenarioTester->setUp(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
  ╳  #24 vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(81): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->setUp(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
  ╳  #25 vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
  ╳  #26 vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(71): Behat\Behat\Hook\Tester\HookableFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
  ╳  #27 vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
  ╳  #28 vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
  ╳  #29 vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(72): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
  ╳  #30 vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
  ╳  #31 vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(70): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
  ╳  #32 vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(146): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
  ╳  #33 vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
  ╳  #34 vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #35 vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(252): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #36 vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(889): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #37 vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #38 vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(102): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #39 vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(124): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #40 vendor/behat/behat/bin/behat(31): Symfony\Component\Console\Application->run()
  ╳  #41 {main}
```

**Comment by BillyMorgan** [comment]
I'm seeing this issue too. Pretty sure I'm doing everything as per the latest readme but unless I hack 'setPublic(false)' to be 'setPublic(true)' I get the aforementioned error. 

Can't help thinking I've done something dumb though since this effectively renders the entire bundle unusable :)

**Comment by Nitseg** [comment]
Hi,
I'm facing exactly the same problem with 1.6 and 1.7.
The issue disappeared after I saw this current conversation and went for 1.5.
I lost a couple of hours on this and could got stuck forever if I hadn't seen this conversation.
For information I'm using service injection for the producer instead of using the container like in the documentation example.
I don't know if it can explain the issue but it may be a lead for the developers.
Regards

**Comment by kosolapovvp** [comment]
Hi,
I'm have the same issue with versions > 1.5.
As @eddiejaoude says, `setPublic(true)` resolve this problem. 
Bundle call this private service `old_sound_rabbit_mq.connection_factory.default` and i got this error. 
With 1.5 all works fine

**Comment by muhammadtaqi** [comment]
I'm also facing this issue. Any working solution yet?
